steps:
    # build the container image
    - name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "gcr.io/$PROJECT_ID/gig-casino:${SHORT_SHA}", "."]
      # push the container image to Container Registry
    - name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/$PROJECT_ID/gig-casino"]
      # deploy container image to Cloud Run
    - name: "gcr.io/cloud-builders/gcloud"
      args:
          [
              "beta",
              "run",
              "deploy",
              "gig-casino",
              "--image",
              "gcr.io/$PROJECT_ID/gig-casino:${SHORT_SHA}",
              "--region",
              "us-central1",
              "--allow-unauthenticated",
              "--platform",
              "managed",
          ]
      env:
          - "PORT=8080"
images:
    - gcr.io/$PROJECT_ID/gig-casino
